name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: cargo test --verbose --all-features

    - name: Run Clippy
      run: cargo clippy --fix --allow-dirty --allow-staged --release --verbose --all-features

    - name: Build
      run: cargo build --release --verbose --all-features
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
